### ISSUE TITLE
Allow_suscriptions = True issue

### ISSUE THREAD

**Issue by mukluk** [jaydenwindle/graphene-subscriptions#17]
Hey Jayden, 

I am having issues subscribing to the "hello world" example from /graphql due to the following error:

"Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True"

Any help would be greatly appreciated.

Thank You,
Gabriel

**Comment by AanandhiVB** [comment]
https://github.com/jaydenwindle/graphene-subscriptions/issues/

Please check this link.

**Comment by jaydenwindle** [comment]
Hey @mukluk!

`graphene-subscriptions` doesn't work out of the box with the Graphene's default GraphiQL client setup. To test subscriptions, I'd recommend using [GraphQL Playground](https://github.com/prisma-labs/graphql-playground). You can also add it to your Django project as a view with [`django-graphql-playground`](https://github.com/jaydenwindle/django-graphql-playground) if you want.

This should definitely be more clearly documented in the readme :)

I'm going to close this for now, but please let me know if you have a hard time getting GraphQL Playground setup and I'll help however I can.
