### ISSUE TITLE
Issue with Model Create Subscriptions

### ISSUE THREAD

**Issue by AanandhiVB** [jaydenwindle/graphene-subscriptions#18]
Hi @jaydenwindle,

I am using this package for subscriptions with graphene. I am facing an issue with the Model Create Subscriptions. 

This is my Model Create Subscription, just as mentioned in the documentation:

```
class Subscription(graphene.ObjectType):

    fruit_created = graphene.Field(FruitsType)

    def resolve_fruit_created(root, info):
        return root.filter( 
            lambda event:
                event.operation == CREATED  and
                isinstance(event.instance, Fruits)
        ).map(lambda event: event.instance)
```

I am testing this in GraphQL Playground.

I keep my subscription running, which is:

```
subscription {
  fruitCreated
  {
    id
    name
    description
  }}
```
And I create a new model instance:
```
mutation{
  createFruit(
    name: "Grape",
    description: "Green/Purple color",
    id: 2
  ){
    fruit
    {
      id
      name
      description
    }
  }
}
```
But my subscription isn't returning anything and it just keeps on listening.

The basic ` hello world! ` subscription is working properly though. 

So what could be the issue? Thank you!

**Comment by jaydenwindle** [comment]
Hey @pikachu-pop!

There's a couple of things that may be an issue here:

1. Have you set up [Channel Layers](https://channels.readthedocs.io/en/latest/topics/channel_layers.html) in your environment? If so, could you share your configuration? `graphene-subscriptions` uses Channel Layers as a pub-sub-like system to trigger subscriptions, so a misconfiguration there can cause subscriptions not to fire.
2. Are your `post_save` signals connected properly? A good way to test this is to wrap the `post_save_subscription` signal handler to see if it gets called by using `pdb` or a `print` statement. Something like: 

```python
# signals.py
def trigger_graphene_subscriptions(sender, **kwargs):
    print('signals are working')
    post_save_subscription(sender, **kwargs)

post_save.connect(trigger_graphene_subscriptions, sender=ChatMessage, dispatch_uid="chat_message_post_save")
```

Let me know if you think either of those things may be the issue!

**Comment by AanandhiVB** [comment]
Hi @jaydenwindle,

Thank you for writing back!

This is my Channel Layer configuration:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
```

I did as you said for checking whether signals are connected properly and unfortunately the print statement didn't work. So I believe that might be the issue?

**Comment by jaydenwindle** [comment]
That Channel Layers config looks good (it should work as long as you've got a Redis server running locally on `6379`), so I'm guessing its a signals issue. 

Take a look at [this issue](https://github.com/jaydenwindle/graphene-subscriptions/issues/1#issuecomment-564069992) where another user encountered a similar problem and see if any of the advice there helps :)

**Comment by AanandhiVB** [comment]
From that thread that you suggested, this is what I tried out:

_app/signals.py_

```
# post_save.connect(trigger_graphene_subscriptions, sender=Fruits, dispatch_uid="fruits_post_save")
post_delete.connect(post_delete_subscription, sender=Fruits, dispatch_uid="fruits_post_delete")

@receiver(post_save, sender=Fruits)
def trigger_graphene_subscriptions(sender, **kwargs):
    print('signals are working')
    post_save_subscription(sender, **kwargs)
```

Still no response though :(

**Comment by jaydenwindle** [comment]
Hey @AanandhiVB - sorry for the late reply on this. If the print statement isn't getting triggered, then it is probably an issue with how you have Django signals set up. Where are you importing `signals.py` from?

 This is a common issue that's been reported. `graphene-subscriptions` v2 will remove the dependency on signals since in favor of something a little more reliable.

**Comment by AanandhiVB** [comment]
Hi @jaydenwindle!

I apologize for not informing this earlier but I got the issue fixed. 

@johnpaul89 thread helped me : https://github.com/jaydenwindle/graphene-subscriptions/issues/1#issuecomment-587926673

Everything is working now and once again thank you for this awesome package.

**Comment by jaydenwindle** [comment]
@AanandhiVB Amazing, glad to hear! You're very welcome :D

**Comment by Cimmanuel** [comment]
I did all these already and mine just keeps listening 🙄🤦🏾‍♂️
@jaydenwindle any thoughts?

**Comment by Cimmanuel** [comment]
> Hi @jaydenwindle,
> 
> I am using this package for subscriptions with graphene. I am facing an issue with the Model Create Subscriptions.
> 
> This is my Model Create Subscription, just as mentioned in the documentation:
> 
> ```
> class Subscription(graphene.ObjectType):
> 
>     fruit_created = graphene.Field(FruitsType)
> 
>     def resolve_fruit_created(root, info):
>         return root.filter( 
>             lambda event:
>                 event.operation == CREATED  and
>                 isinstance(event.instance, Fruits)
>         ).map(lambda event: event.instance)
> ```
> 
> I am testing this in GraphQL Playground.
> 
> I keep my subscription running, which is:
> 
> ```
> subscription {
>   fruitCreated
>   {
>     id
>     name
>     description
>   }}
> ```
> 
> And I create a new model instance:
> 
> ```
> mutation{
>   createFruit(
>     name: "Grape",
>     description: "Green/Purple color",
>     id: 2
>   ){
>     fruit
>     {
>       id
>       name
>       description
>     }
>   }
> }
> ```
> 
> But my subscription isn't returning anything and it just keeps on listening.
> 
> The basic `hello world!` subscription is working properly though.
> 
> So what could be the issue? Thank you!

In my case, even the basic hello world subscription just keeps listening

**Comment by jaydenwindle** [comment]
Hey @Cimmanuel! I'd love to help :)

Can you share some more details on how you've configured GraphQL Playground to connect to your API?

**Comment by Cimmanuel** [comment]
@jaydenwindle please give me about 30 minutes to get to my computer. I'm currently away. Very sorry for the delay

**Comment by Cimmanuel** [comment]
@jaydenwindle here are snippets:

`settings.py`
```python
INSTALLED_APPS = (
    ...
    'graphene_subscriptions',
    'channels',
    'graphql_playground'
)

...
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
```

`routing.py`
```python
application = ProtocolTypeRouter({
    'websocket': URLRouter([
        path('graphql/', GraphqlSubscriptionConsumer)
    ]),
})
```

`urls.py`
```python
class GraphQLCustomCoreBackend(GraphQLCoreBackend):
    def __init__(self, executor=None):
        super().__init__(executor)
        self.execute_params['allow_subscriptions'] = True

urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(
        FileUploadGraphQLView.as_view(
            graphiql=True, backend=GraphQLCustomCoreBackend()))),
    path('playground/', GraphQLPlaygroundView.as_view(endpoint="/graphql/")),
]
```

`schema.py (root)`
```python
class Query(path.to.schema.Query, graphene.ObjectType):
    pass

class Subscription(path.to.schema.Subscription, graphene.ObjectType):
    pass

schema = graphene.Schema(
    query=Query,
    subscription=Subscription
)
```

`schema.py (app)`
```python
class Subscription(graphene.ObjectType):
    hello = graphene.String()
    user_created = graphene.Field(UserType)

    def resolve_hello(root, info):
        return Observable.interval(3000).map(lambda i: "hello world!")

    def resolve_user_created(root, info):
        return root.filter(
            lambda event:
                event.operation == CREATED and
                isinstance(event.instance, User)
        ).map(lambda event: event.instance)
```

`signals.py`
```python
@receiver(post_save, sender=models.User)
def trigger_subscriptions(sender, **kwargs):
    print('Subscription signals works!')
    post_save_subscription(sender, **kwargs)
```

I have the ready method of AppConfig subclass importing signals so the signal above works (I get `Subscription signal works` in the terminal). I don't know what else to do.

**Comment by jaydenwindle** [comment]
@Cimmanuel Got it, thanks for the extra info :)

How are you running your Django server? Are you using `./manage.py runserver` or something else?

**Comment by Cimmanuel** [comment]
@jaydenwindle The application is dockerized.

**Comment by jaydenwindle** [comment]
@Cimmanuel Can you share your dockerfile? Specifically the command that is being used to run the server?

**Comment by Cimmanuel** [comment]
@jaydenwindle 
```
FROM python:3.7.4-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && python -m pip install --upgrade pip \
    && pip install pipenv
COPY ./Pipfile /usr/src/app/Pipfile
COPY ./Pipfile.lock /usr/src/app/Pipfile.lock
RUN python -m pipenv install

# copy project
COPY . /usr/src/app/

COPY ./start.sh /start.sh

RUN chmod +x /start.sh
```

`start.sh`
```sh
#! /usr/bin/env bash

function manage_app() {
    pipenv run python manage.py migrate
    pipenv run python manage.py collectstatic --no-input --clear
}

function start_development() {
    # use django runserver as development server here.
    manage_app
    pipenv run python manage.py runserver 0.0.0.0:8000
}

function start_production() {
    # use gunicorn for production server here
    manage_app
    gunicorn api.wsgi -w 4 -b 0.0.0.0:8000 --chdir=/usr/src/app --log-file -
}

if [ ${DEBUG} == "True" ]
then
    # use development server
    start_development
else
    # use production server
    start_production
fi
```
It's basically still `manage.py runserver`

**Comment by jaydenwindle** [comment]
@Cimmanuel Got it :)

And you're running the dockerized app with `DEBUG="True"`? Trying to run graphene-subscriptions with `gunicorn` will not work since channels requires an ASGI server.

Can you create a repo that reproduces the issue so that I can look into it and diagnose further?

**Comment by Cimmanuel** [comment]
@jaydenwindle so I did this in playground:

```
subscription {
  userCreated {
    id
    firstName
    lastName
  }
}
```

My logs when I tried to create a user object
```
System check identified no issues (0 silenced).
July 13, 2020 - 20:04:15
Django version 2.2.14, using settings 'cnapi.settings'
Starting ASGI/Channels version 2.3.1 development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Subscription signals works!
HTTP POST /graphql/ 200 [0.54, 172.18.0.1:38920]
```

**Comment by Cimmanuel** [comment]
> @Cimmanuel Got it :)
> 
> And you're running the dockerized app with `DEBUG="True"`? Trying to run graphene-subscriptions with `gunicorn` will not work since channels requires an ASGI server.
> 
> Can you create a repo that reproduces the issue so that I can look into it and diagnose further?

@jaydenwindle I can't do this. I'm very sorry!

**Comment by Cimmanuel** [comment]
@jaydenwindle still haven't heard from you. I guess you are very busy. However, this is what I found on the client-side:

`DOMException: Failed to construct 'WebSocket': The URL '/graphql/' is invalid.`
I think this is what's wrong. But I don't see anything wrong with my URL configuration. Now, I'm confused!

**Comment by Cimmanuel** [comment]
Never mind Jayden. This was as a result of specifying a relative URL as endpoint value for GraphQLPlaygroundView. It only takes an absolute URL. Bottomline, IT WORKS!

**Comment by jaydenwindle** [comment]
@Cimmanuel Ah, ok! I should probably make sure that is documented more clearly. Glad you got it working :)
